version: 2

services:
  web:
    source: .
    env:
      PORT: 8000
      DATABASE_URL: ${{ RAILWAY_DATABASE_URL }}
      DJANGO_SETTINGS_MODULE: myproject.settings.production
      SECRET_KEY: ${{ RAILWAY_SECRET_KEY }}
      DEBUG: false
      ALLOWED_HOSTS: ${{ RAILWAY_PUBLIC_DOMAIN }}
    build:
      command: |
        cd myproject
        python manage.py collectstatic --noinput
        python manage.py migrate
    run:
      command: cd myproject && gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    
  database:
    image: postgres:15
    env:
      POSTGRES_DB: djangodb
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${{ RAILWAY_DATABASE_PASSWORD }}